'use client';
import {useMemo,useState} from 'react';
import './forms.css';

const modules={
 dashboard:{name:'Tableau de bord',description:'Contrôle de la journée, du stock et de la trésorerie.'},
 purchases:{name:'Achats fournisseurs',description:'Entrées de marchandises dans le stock général.',fields:[['supplier','Fournisseur'],['reference','Référence achat'],['product','Produit'],['quantity','Quantité','number'],['cost','Prix d’achat','number']]},
 stock:{name:'Stock & affectations',description:'Transférer et suivre le stock entre le bureau et les agents.',fields:[['agent','Agent destinataire'],['product','Produit'],['quantity','Quantité à affecter','number'],['note','Motif / note']]},
 sales:{name:'Ventes & rapports agents',description:'Saisir plusieurs produits vendus par un agent et l’encaissement.',fields:[['agent','Agent'],['product','Produit vendu'],['quantity','Quantité vendue','number'],['price','Prix unitaire','number'],['cash','Montant remis','number']]},
 finance:{name:'Trésorerie & dépenses',description:'Enregistrer toute sortie, tout versement et clôturer la journée.',fields:[['category','Catégorie'],['amount','Montant','number'],['note','Motif'],['proof','Référence justificatif']]},
 inventory:{name:'Inventaires',description:'Comparer le stock théorique et physique, puis justifier les écarts.',fields:[['location','Emplacement'],['product','Produit'],['physical','Quantité physique','number'],['justification','Justification de l’écart']]},
 reports:{name:'Rapports',description:'Consulter les résultats par jour, semaine, mois et agent.'}
};
const nav=['dashboard','purchases','stock','sales','finance','inventory','reports'];
export default function Page(){const [view,setView]=useState('dashboard');const [saved,setSaved]=useState([]);const screen=modules[view];return <main className="shell"><aside><div className="brand">ZandEx<small>AFRICA · OPERATIONS</small></div><div className="office"><b>BUREAU PRINCIPAL</b><br/>Kinshasa · Journée ouverte</div><nav>{nav.map(key=><button key={key} className={view===key?'active':''} onClick={()=>setView(key)}>{modules[key].name}</button>)}</nav><footer>Marie Kalonji<br/><span>Gestionnaire</span></footer></aside><section className="workspace"><header><div><b>{screen.name.toUpperCase()}</b><small>24 septembre 2026 · Bureau principal</small></div><span className="live">● Session ouverte</span></header><div className="content"><div className="eyebrow">ESPACE DE TRAVAIL</div><h1>{screen.name}</h1><p>{screen.description}</p>{view==='dashboard'?<Dashboard onOpen={()=>setView('sales')}/>:view==='reports'?<Reports saved={saved}/>:<OperationForm screen={screen} onSave={entry=>setSaved([...saved,entry])}/>}</div></section></main>}
function Dashboard({onOpen}){return <><div className="metrics"><Metric primary label="Trésorerie disponible" value="1 284 000 FC"/><Metric label="Ventes terrain" value="1 230 000 FC"/><Metric label="Stock bureau" value="482 u."/><Metric label="Chez les agents" value="196 u."/></div><div className="grid"><section className="panel"><div className="panelhead"><b>Actions prioritaires</b><button className="primary" onClick={onOpen}>Saisir un rapport agent</button></div><div className="item"><b>Rapport attendu — Junior K.</b><span>Stock confié : 34 unités</span></div><div className="item"><b>Écart d’inventaire à justifier</b><span>Détergent Citrus 1L · −2 unités</span></div></section><section className="panel"><div className="panelhead"><b>Journal récent</b></div><div className="item"><b>Rapport validé · Clarisse M.</b><span>+ 186 000 FC · 10:42</span></div><div className="item"><b>Ravitaillement · Jesse B.</b><span>20 unités · 09:18</span></div></section></div></>}
function Metric({label,value,primary}){return <div className={'metric '+(primary?'main':'')}><small>{label}</small><b>{value}</b></div>}
function OperationForm({screen,onSave}){const [values,setValues]=useState({});const [message,setMessage]=useState('');function submit(e){e.preventDefault();const missing=screen.fields.filter(([id])=>!values[id]);if(missing.length){setMessage('Veuillez compléter les champs obligatoires.');return}onSave({module:screen.name,at:new Date().toLocaleString('fr-FR'),values});setMessage('Opération enregistrée dans le journal de traçabilité.');setValues({})}return <form className="operation-form" onSubmit={submit}><h2>Nouvelle opération</h2>{screen.fields.map(([id,label,type])=><label key={id}>{label}<input type={type||'text'} min={type==='number'?0:undefined} required value={values[id]||''} onChange={e=>setValues({...values,[id]:e.target.value})}/></label>)}<button className="primary" type="submit">Valider et tracer</button>{message&&<p className="form-message">{message}</p>}</form>}
function Reports({saved}){const rows=useMemo(()=>saved.length?saved:[{module:'Aucune opération validée',at:'—'}],[saved]);return <section className="panel"><div className="panelhead"><b>Journal de travail</b><span>{saved.length} opération(s)</span></div><table><thead><tr><th>Module</th><th>Date</th><th>État</th></tr></thead><tbody>{rows.map((row,i)=><tr key={i}><td>{row.module}</td><td>{row.at}</td><td>Traçable</td></tr>)}</tbody></table></section>}
